[package]
name = "dyson"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/hayas1/dyson"
homepage = "https://hayas1.github.io/dyson/dyson"
license = "MIT"
readme = "./README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
